-👷 Olá, me chamo wenderson Edgar tenho 32
Anos sou casado tenho uma filha.
-🛰️ Tenho interesse em trabalhar na área de
Desenvolvimento de sistemas e engenharia de 
software.
-🌏 Facilidade em desenvolver Projetos 
Sustentáveis, que Proporciona Diminuição
de custo, aumento de produtividade. 
-🐘 Criar uma base solída e continua em 
um processo evolutivo, com isso um novo 
leque de oportunidades.
-👩‍🏫 Certeza que posso transformar o
imaginário em uma chance real de 
crescimento. 
-🌀independente de qual área for o seguimento, 
posso prover soluções que vai além dos
resultados esperados, posso integrar a esses
resultado um leque de novas oportunidades.
- 🔍Procuro um espaço na sua empresa para 
atuar no desenvolvimento de produtos e 
tecnologias inovadores disrrupitoveis.
-📲 entre em contato no n° 55 61-9-94508086
-📬 email: wendersonsilva32570@gmail.com
-💬 LinkedIn: https://www.linkedin.com/in/wendersonanalistadesenvolvedorsistema
 
<!---
wendersonEdgar32570/wendersonEdgar32570 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
